server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yun-user?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml